[[language]]
name = "markdown"
file-types = ["md", "MD"]

[[language]]
name = "python"
language-servers = ["pyright"]
# TODO: not sure if this actually works
auto-format = true

[[language]]
name = "go"
auto-format = true

[[language]]
name = "kotlin"
auto-format = true

[[language]]
name = "java"
auto-format = true

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "yamlfmt", args = ['-'] }
auto-format = true

[[language]]
name = "json"
auto-format = true

[[language]]
name = "toml"
# https://github.com/tamasfe/taplo/issues/580#issuecomment-2004174721
roots = ["."]
auto-format = true
