[[language]]
name = "scheme"
file-types = [
  "scm",
  "scheme",
  "sb",     # sandbox-exec configs
]

[[language]]
name = "markdown"
file-types = ["md", "MD"]

[[language]]
name = "python"
language-servers = ["pyright"]
# TODO: not sure if this actually works
auto-format = true

[[language]]
name = "go"
auto-format = true

[[language]]
name = "kotlin"
auto-format = true

[[language]]
name = "java"
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "yamlfmt", args = ['-'] }
auto-format = true

[[language]]
name = "json"
auto-format = true

[[language]]
name = "toml"
# https://github.com/tamasfe/taplo/issues/580#issuecomment-2004174721
roots = ["."]
auto-format = true

[[language]]
name = "bash"
formatter = { command = "shfmt", args = [
  "--indent",
  "0",
  "--binary-next-line",
  "--case-indent",
  "--space-redirects",
  "--simplify",
] }
auto-format = true
