# Author : broke <broke@in-fucking.space>
# The theme uses the gruvbox dark palette with soft contrast: github.com/morhetz/gruvbox

inherits = "gruvbox_dark_soft"

"ui.background" = { fg = "white"}
"ui.background.separator" = { fg = "gray" }
