swipe:
  3: 
    left: 
      command: 'i3-msg workspace next_on_output'
    right: 
      command: 'i3-msg workspace prev_on_output'
    up: 
      command: 'rofi -show drun'
    down: 
      command: 'killall rofi || xdotool key Escape'
  4:
    left: 
      command: 'i3-msg workspace back_and_forth'
    right: 
      command: 'i3-msg workspace back_and_forth'
    up: 
      command: 'loginctl lock-session'
    down: 
      command: 'i3-msg workspace 21'
pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
     command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.2
  pinch: 0.4

interval:
  swipe: 0.5
  pinch: 0.4
