start-at-login = true

# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

after-startup-command = [
  # https://github.com/FelixKratz/JankyBorders
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0x00494d64 width=5.0 hidpi=on',
  # https://github.com/FelixKratz/SketchyBar
  'exec-and-forget sketchybar'
]

enable-normalization-flatten-containers = false 
default-root-container-layout = 'tiles'
accordion-padding = 0

[gaps]
# outer.left = 5
outer.top = [ { monitor."built-in" = 0 }, 30 ]
# outer.right = 5
# outer.bottom = 5
inner.horizontal = 5
inner.vertical = 5

[mode.main.binding]

alt-ctrl-shift-s = 'layout v_accordion'
alt-ctrl-shift-t = 'layout h_accordion'
alt-ctrl-s = 'layout v_accordion'
alt-ctrl-t = 'layout h_accordion'
alt-ctrl-shift-b = 'layout tiles'
alt-comma = 'split vertical'
alt-period = 'split horizontal'

cmd-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

ctrl-alt-shift-h = 'join-with left'
ctrl-alt-shift-j = 'join-with down'
ctrl-alt-shift-k = 'join-with up'
ctrl-alt-shift-l = 'join-with right'
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-tab = 'workspace-back-and-forth'
alt-leftSquareBracket = 'exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace --wrap-around prev'
alt-rightSquareBracket = 'exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace --wrap-around next'
alt-semicolon = 'focus-monitor --wrap-around left'
alt-quote = 'focus-monitor --wrap-around right'
alt-shift-semicolon = 'move-node-to-monitor --wrap-around left'
alt-shift-quote = 'move-node-to-monitor --wrap-around right'

alt-backtick = 'workspace 1'
alt-1 = 'workspace 2'
alt-2 = 'workspace 3'
alt-3 = 'workspace 4'
alt-4 = 'workspace 5'
alt-5 = 'workspace 6'
alt-6 = 'workspace 7'
alt-7 = 'workspace 8'
alt-8 = 'workspace 9'
alt-9 = 'workspace 10'
alt-0 = 'workspace 11'

alt-shift-leftSquareBracket = 'move-node-to-workspace prev'
alt-shift-rightSquareBracket = 'move-node-to-workspace next'
alt-shift-backtick = 'move-node-to-workspace 1'
alt-shift-1 = 'move-node-to-workspace 2'
alt-shift-2 = 'move-node-to-workspace 3'
alt-shift-3 = 'move-node-to-workspace 4'
alt-shift-4 = 'move-node-to-workspace 5'
alt-shift-5 = 'move-node-to-workspace 6'
alt-shift-6 = 'move-node-to-workspace 7'
alt-shift-7 = 'move-node-to-workspace 8'
alt-shift-8 = 'move-node-to-workspace 9'
alt-shift-9 = 'move-node-to-workspace 10'
alt-shift-0 = 'move-node-to-workspace 11'

alt-shift-m = 'macos-native-minimize'
alt-shift-n = 'fullscreen --no-outer-gaps'
alt-f = 'fullscreen'
alt-shift-f = 'layout tiling floating'
alt-shift-q = 'close'

ctrl-shift-s = 'mode service'
alt-r = 'mode resize'

alt-enter = 'exec-and-forget open -a alacritty -n'
alt-e = 'exec-and-forget open $HOME'
alt-ctrl-d = 'exec-and-forget open -a slack'
alt-s = 'exec-and-forget ~/scripts/scratchpad.sh'
alt-shift-s = 'exec-and-forget open -a "System Settings"'
alt-ctrl-o = 'exec-and-forget ~/scripts/switchmic.sh'
alt-p = 'exec-and-forget skhd -k "alt + shift - up"'
alt-n = 'exec-and-forget skhd -k "alt + shift - down"'
alt-b = 'exec-and-forget pgrep sketchybar && sketchybar --reload || sketchybar'
alt-shift-c = 'reload-config'


[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
shift-h = 'resize width -5'
shift-j = 'resize height +5'
shift-k = 'resize height -5'
shift-l = 'resize width +5'
enter = 'mode main'
esc = 'mode main'
alt-r = 'mode main'

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'

[[on-window-detected]]
if.window-title-regex-substring = 'scratchpad'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.cisco.anyconnect.gui'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 5'

[workspace-to-monitor-force-assignment]
4 = 'secondary'
5 = 'secondary'
9 = 'secondary'
10 = 'secondary'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']
