#!/bin/bash
array=( $@ )
if test $# -eq 1; then
	# use the home directory as the destination
	array+=(".")
fi

len=${#array[@]}

printf "%s\n" "${array[@]:0:$len-1}" |
	parallel scp -r {} "z5218547@login.cse.unsw.edu.au:~/${array[@]: -1}"
